### ISSUE TITLE
弹出层在youtube评论上显示位置不正确

### ISSUE THREAD

**Issue by williamdu2877** [jinntrance/shanbay-crx#59] opened 2016-11-02 02:14 UTC
![screen shot 2016-11-02 at 10 12 24 am](https://cloud.githubusercontent.com/assets/1171540/19914376/257a18ca-a0e5-11e6-8ec5-48edfef80122.png)

**Comment by jinntrance** [comment] 2016-11-03 04:45
duplicate of #57

**Closed by jinntrance** 2016-11-03 04:45 UTC

**Comment by jinntrance** [comment] 2017-07-20 12:03
duplicate of #46
